name: Deploy lending

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout проекта
      - name: Checkout code
        uses: actions/checkout@v3

      # Настройка SSH
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Деплой на удалённый сервер
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          cd /web/lending-amincode/
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S git pull origin main
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl restart nginx
          EOF
